### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by luigino** [Toilal/rebulk#16]
Packaging rebulk 0.9.0 for openSUSE linux.
The [log](https://github.com/Toilal/rebulk/files/2342340/rebulk27.txt) shows the errors for python 2.7, but it's the same with 3.6.

**Comment by Toilal** [comment]
No test are failing here. It seems there's an offset between effective line numbers and returned one. It this still an issue ?

**Comment by luigino** [comment]
[No apparent change.](https://github.com/Toilal/rebulk/files/2475127/rebulk-1.0.0_py27.txt)

**Comment by labrys** [comment]
Tested on Windows 10 with python 2.7, 3.6, and 3.7 - all tests pass.

**Comment by Toilal** [comment]
Same with Ubuntu here, and tests are fine on TravisCI too.
